/*
 * Copyright (C) 2011 Darren Salt
 *
 * Licensed under the Apache License, Version 2.0 (the "Licence"); you may
 * not use this file except in compliance with the Licence. You may obtain
 * a copy of the Licence at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the Licence is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * Licence for the specific language governing permissions and limitations
 * under the Licence.
 */

package dev.devkey.keyboard

import android.util.Log
import android.view.inputmethod.EditorInfo
import dev.devkey.keyboard.ui.keyboard.KeyCodes

/**
 * Compose key sequence handler.
 *
 * @param onComposedText Callback to send composed text to the IME.
 * @param updateShiftState Callback to refresh shift key state after composing.
 * @param editorInfoProvider Provides the current [EditorInfo] for shift state updates.
 */
open class ComposeSequence(
    protected val onComposedText: (CharSequence) -> Unit,
    private val updateShiftState: (EditorInfo?) -> Unit,
    private val editorInfoProvider: () -> EditorInfo?
) {

    protected var composeBuffer: StringBuilder = StringBuilder(10)

    init {
        clear()
    }

    fun clear() {
        composeBuffer.setLength(0)
    }

    fun hasBufferedKeys(): Boolean = composeBuffer.isNotEmpty()

    fun bufferKey(code: Char) {
        composeBuffer.append(code)
    }

    /**
     * Returns the composed string if sequence is complete,
     * empty string if sequence is unrecognised,
     * or null if the sequence is valid but incomplete.
     */
    fun executeToString(code: Int): String? {
        var mutableCode = code
        val ks = KeyboardSwitcher.getInstance()
        if (ks.getShiftState() == Keyboard.SHIFT_LOCKED
            && ks.isAlphabetMode()
            && Character.isLowerCase(mutableCode)
        ) {
            mutableCode = mutableCode.toChar().uppercaseChar().code
        }
        bufferKey(mutableCode.toChar())
        updateShiftState(editorInfoProvider())

        val composed = get(composeBuffer.toString())
        if (composed != null) {
            // If we get here, we have a complete compose sequence
            return composed
        } else if (!isValid(composeBuffer.toString())) {
            // If we get here, then the sequence typed isn't recognised
            return ""
        }
        return null
    }

    open fun execute(code: Int): Boolean {
        val composed = executeToString(code)
        if (composed != null) {
            clear()
            onComposedText(composed)
            return false
        }
        return true
    }

    fun execute(sequence: CharSequence): Boolean {
        var result = true
        for (i in sequence.indices) {
            result = execute(sequence[i].code)
        }
        return result // only last one matters
    }

    companion object {
        private const val TAG = "DevKey/ComposeSequence"

        private val mMap: MutableMap<String, String> = HashMap(1024)

        private val mPrefixes: MutableSet<String> = HashSet(2048)

        @JvmStatic
        internal fun getMap(): Map<String, String> = mMap

        @JvmStatic
        internal fun getPrefixes(): Set<String> = mPrefixes

        // Convenience aliases for use in compose strings
        val UP: Char          = KeyCodes.KEYCODE_DPAD_UP.toChar()
        val DOWN: Char        = KeyCodes.KEYCODE_DPAD_DOWN.toChar()
        val LEFT: Char        = KeyCodes.KEYCODE_DPAD_LEFT.toChar()
        val RIGHT: Char       = KeyCodes.KEYCODE_DPAD_RIGHT.toChar()
        val COMPOSE: Char     = KeyCodes.KEYCODE_DPAD_CENTER.toChar()
        val PAGE_UP: Char     = KeyCodes.KEYCODE_PAGE_UP.toChar()
        val PAGE_DOWN: Char   = KeyCodes.KEYCODE_PAGE_DOWN.toChar()
        val ESCAPE: Char      = KeyCodes.ESCAPE.toChar()
        val DELETE: Char      = KeyCodes.KEYCODE_FORWARD_DEL.toChar()
        val CAPS_LOCK: Char   = KeyCodes.KEYCODE_CAPS_LOCK.toChar()
        val SCROLL_LOCK: Char = KeyCodes.KEYCODE_SCROLL_LOCK.toChar()
        val SYSRQ: Char       = KeyCodes.KEYCODE_SYSRQ.toChar()
        val BREAK: Char       = KeyCodes.KEYCODE_BREAK.toChar()
        val HOME: Char        = KeyCodes.KEYCODE_HOME.toChar()
        val END: Char         = KeyCodes.KEYCODE_END.toChar()
        val INSERT: Char      = KeyCodes.KEYCODE_INSERT.toChar()
        val F1: Char          = KeyCodes.KEYCODE_FKEY_F1.toChar()
        val F2: Char          = KeyCodes.KEYCODE_FKEY_F2.toChar()
        val F3: Char          = KeyCodes.KEYCODE_FKEY_F3.toChar()
        val F4: Char          = KeyCodes.KEYCODE_FKEY_F4.toChar()
        val F5: Char          = KeyCodes.KEYCODE_FKEY_F5.toChar()
        val F6: Char          = KeyCodes.KEYCODE_FKEY_F6.toChar()
        val F7: Char          = KeyCodes.KEYCODE_FKEY_F7.toChar()
        val F8: Char          = KeyCodes.KEYCODE_FKEY_F8.toChar()
        val F9: Char          = KeyCodes.KEYCODE_FKEY_F9.toChar()
        val F10: Char         = KeyCodes.KEYCODE_FKEY_F10.toChar()
        val F11: Char         = KeyCodes.KEYCODE_FKEY_F11.toChar()
        val F12: Char         = KeyCodes.KEYCODE_FKEY_F12.toChar()
        val NUM_LOCK: Char    = KeyCodes.KEYCODE_NUM_LOCK.toChar()

        private val keyNames: Map<Char, String> = mapOf(
            '"' to "quot",
            UP to "\u2191",
            DOWN to "\u2193",
            LEFT to "\u2190",
            RIGHT to "\u2192",
            COMPOSE to "\u25EF",
            PAGE_UP to "PgUp",
            PAGE_DOWN to "PgDn",
            ESCAPE to "Esc",
            DELETE to "Del",
            CAPS_LOCK to "Caps",
            SCROLL_LOCK to "Scroll",
            SYSRQ to "SysRq",
            BREAK to "Break",
            HOME to "Home",
            END to "End",
            INSERT to "Insert",
            F1 to "F1",
            F2 to "F2",
            F3 to "F3",
            F4 to "F4",
            F5 to "F5",
            F6 to "F6",
            F7 to "F7",
            F8 to "F8",
            F9 to "F9",
            F10 to "F10",
            F11 to "F11",
            F12 to "F12",
            NUM_LOCK to "Num"
        )

        @JvmStatic
        fun get(key: String?): String? {
            if (key.isNullOrEmpty()) {
                return null
            }
            return mMap[key]
        }

        private fun showString(input: String): String {
            val out = StringBuilder(input)
            out.append("{")
            for (i in input.indices) {
                if (i > 0) out.append(",")
                out.append(input[i].code)
            }
            out.append("}")
            return out.toString()
        }

        private fun isValid(partialKey: String?): Boolean {
            if (partialKey.isNullOrEmpty()) {
                return false
            }
            return mPrefixes.contains(partialKey)
        }

        @JvmStatic
        fun format(seq: String): String {
            val output = StringBuilder()
            var quoted = false
            val end = seq.length

            for (i in 0 until end) {
                val c = seq[i]
                val keyName = keyNames[c]
                if (keyName != null) {
                    output.append(if (quoted) "\" " else " ")
                    output.append(keyName)
                    quoted = false
                } else {
                    if (!quoted) {
                        output.append(if (output.isNotEmpty()) " \"" else "\"")
                    }
                    if (c < ' ' || c == '"' || c == '\\') {
                        output.append("\\")
                        output.append(if (c < ' ') (c.code + 64).toChar() else c)
                    } else {
                        output.append(c)
                    }
                    quoted = true
                }
            }
            if (quoted) {
                output.append('"')
            }

            return output.toString()
        }

        @JvmStatic
        fun put(key: String, value: String) {
            var found = false

            if (key.isEmpty() || value.isEmpty()) return

            if (mMap.containsKey(key)) {
                Log.w(TAG, "compose sequence is a duplicate: ${format(key)}")
            } else if (mPrefixes.contains(key)) {
                Log.w(TAG, "compose sequence is a subset: ${format(key)}")
            }

            mMap[key] = value
            for (i in 1 until key.length) {
                val substr = key.substring(0, i)
                found = found or mMap.containsKey(substr)
                mPrefixes.add(substr)
            }

            if (found) {
                Log.w(TAG, "compose sequence is a superset: ${format(key)}")
            }
        }

        init {
            reset()
        }

        private fun reset() {
            put("++", "#")
            put("' ", "'")
            put(" '", "'")
            put("AT", "@")
            put("((", "[")
            put("//", "\\")
            put("/<", "\\")
            put("</", "\\")
            put("))", "]")
            put("^ ", "^")
            put(" ^", "^")
            put("> ", "^")
            put(" >", "^")
            put("` ", "`")
            put(" `", "`")
            put(", ", "\u00b8")
            put(" ,", "\u00b8")
            put("(-", "{")
            put("-(", "{")
            put("/^", "|")
            put("^/", "|")
            put("VL", "|")
            put("LV", "|")
            put("vl", "|")
            put("lv", "|")
            put(")-", "}")
            put("-)", "}")
            put("~ ", "~")
            put(" ~", "~")
            put("- ", "~")
            put(" -", "~")
            put("  ", "\u00a0")
            put(" .", "\u00a0")
            put("oc", "\u00a9")
            put("oC", "\u00a9")
            put("Oc", "\u00a9")
            put("OC", "\u00a9")
            put("or", "\u00ae")
            put("oR", "\u00ae")
            put("Or", "\u00ae")
            put("OR", "\u00ae")
            put(".>", "\u203a")
            put(".<", "\u2039")
            put("..", "\u2026")
            put(".-", "\u00b7")
            put(".=", "\u2022")
            put("!^", "\u00a6")
            put("!!", "\u00a1")
            put("p!", "\u00b6")
            put("P!", "\u00b6")
            put("+-", "\u00b1")
            put("??", "\u00bf")
            put("-d", "\u0111")
            put("-D", "\u0110")
            put("ss", "\u00df")
            put("SS", "\u1e9e")
            put("oe", "\u0153")
            put("OE", "\u0152")
            put("ae", "\u00e6")
            put("AE", "\u00c6")
            put("oo", "\u00b0")
            put("\"\\", "\u301d")
            put("\"/", "\u301e")
            put("<<", "\u00ab")
            put(">>", "\u00bb")
            put("<'", "\u2018")
            put("'<", "\u2018")
            put(">'", "\u2019")
            put("'>", "\u2019")
            put(",'", "\u201a")
            put("',", "\u201a")
            put("<\"", "\u201c")
            put("\"<", "\u201c")
            put(">\"", "\u201d")
            put("\">", "\u201d")
            put(",\"", "\u201e")
            put("\",", "\u201e")
            put("%o", "\u2030")
            put("CE", "\u20a0")
            put("C/", "\u20a1")
            put("/C", "\u20a1")
            put("Cr", "\u20a2")
            put("Fr", "\u20a3")
            put("L=", "\u20a4")
            put("=L", "\u20a4")
            put("m/", "\u20a5")
            put("/m", "\u20a5")
            put("N=", "\u20a6")
            put("=N", "\u20a6")
            put("Pt", "\u20a7")
            put("Rs", "\u20a8")
            put("W=", "\u20a9")
            put("=W", "\u20a9")
            put("d-", "\u20ab")
            put("C=", "\u20ac")
            put("=C", "\u20ac")
            put("c=", "\u20ac")
            put("=c", "\u20ac")
            put("E=", "\u20ac")
            put("=E", "\u20ac")
            put("e=", "\u20ac")
            put("=e", "\u20ac")
            put("|c", "\u00a2")
            put("c|", "\u00a2")
            put("c/", "\u00a2")
            put("/c", "\u00a2")
            put("L-", "\u00a3")
            put("-L", "\u00a3")
            put("Y=", "\u00a5")
            put("=Y", "\u00a5")
            put("fs", "\u017f")
            put("fS", "\u017f")
            put("--.", "\u2013")
            put("---", "\u2014")
            put("#b", "\u266d")
            put("#f", "\u266e")
            put("##", "\u266f")
            put("so", "\u00a7")
            put("os", "\u00a7")
            put("ox", "\u00a4")
            put("xo", "\u00a4")
            put("PP", "\u00b6")
            put("No", "\u2116")
            put("NO", "\u2116")
            put("?!", "\u2e18")
            put("!?", "\u203d")
            put("CCCP", "\u262d")
            put("OA", "\u24b6")
            put("<3", "\u2665")
            put(":)", "\u263a")
            put(":(", "\u2639")
            put(",-", "\u00ac")
            put("-,", "\u00ac")
            put("^_a", "\u00aa")
            put("^2", "\u00b2")
            put("^3", "\u00b3")
            put("mu", "\u00b5")
            put("^1", "\u00b9")
            put("^_o", "\u00ba")
            put("14", "\u00bc")
            put("12", "\u00bd")
            put("34", "\u00be")
            put("`A", "\u00c0")
            put("'A", "\u00c1")
            put("^A", "\u00c2")
            put("~A", "\u00c3")
            put("\"A", "\u00c4")
            put("oA", "\u00c5")
            put(",C", "\u00c7")
            put("`E", "\u00c8")
            put("'E", "\u00c9")
            put("^E", "\u00ca")
            put("\"E", "\u00cb")
            put("`I", "\u00cc")
            put("'I", "\u00cd")
            put("^I", "\u00ce")
            put("\"I", "\u00cf")
            put("DH", "\u00d0")
            put("~N", "\u00d1")
            put("`O", "\u00d2")
            put("'O", "\u00d3")
            put("^O", "\u00d4")
            put("~O", "\u00d5")
            put("\"O", "\u00d6")
            put("xx", "\u00d7")
            put("/O", "\u00d8")
            put("`U", "\u00d9")
            put("'U", "\u00da")
            put("^U", "\u00db")
            put("\"U", "\u00dc")
            put("'Y", "\u00dd")
            put("TH", "\u00de")
            put("`a", "\u00e0")
            put("'a", "\u00e1")
            put("^a", "\u00e2")
            put("~a", "\u00e3")
            put("\"a", "\u00e4")
            put("oa", "\u00e5")
            put(",c", "\u00e7")
            put("`e", "\u00e8")
            put("'e", "\u00e9")
            put("^e", "\u00ea")
            put("\"e", "\u00eb")
            put("`i", "\u00ec")
            put("'i", "\u00ed")
            put("^i", "\u00ee")
            put("\"i", "\u00ef")
            put("dh", "\u00f0")
            put("~n", "\u00f1")
            put("`o", "\u00f2")
            put("'o", "\u00f3")
            put("^o", "\u00f4")
            put("~o", "\u00f5")
            put("\"o", "\u00f6")
            put(":-", "\u00f7")
            put("-:", "\u00f7")
            put("/o", "\u00f8")
            put("`u", "\u00f9")
            put("'u", "\u00fa")
            put("^u", "\u00fb")
            put("\"u", "\u00fc")
            put("'y", "\u00fd")
            put("th", "\u00fe")
            put("\"y", "\u00ff")
            put("_A", "\u0100")
            put("_a", "\u0101")
            put("UA", "\u0102")
            put("bA", "\u0102")
            put("Ua", "\u0103")
            put("ba", "\u0103")
            put(";A", "\u0104")
            put(",A", "\u0104")
            put(";a", "\u0105")
            put(",a", "\u0105")
            put("'C", "\u0106")
            put("'c", "\u0107")
            put("^C", "\u0108")
            put("^c", "\u0109")
            put(".C", "\u010a")
            put(".c", "\u010b")
            put("cC", "\u010c")
            put("cc", "\u010d")
            put("cD", "\u010e")
            put("cd", "\u010f")
            put("/D", "\u0110")
            put("/d", "\u0111")
            put("_E", "\u0112")
            put("_e", "\u0113")
            put("UE", "\u0114")
            put("bE", "\u0114")
            put("Ue", "\u0115")
            put("be", "\u0115")
            put(".E", "\u0116")
            put(".e", "\u0117")
            put(";E", "\u0118")
            put(",E", "\u0118")
            put(";e", "\u0119")
            put(",e", "\u0119")
            put("cE", "\u011a")
            put("ce", "\u011b")
            //put("ff", "\ufb00") // Not usable, interferes with ffi/ffl prefix
            put("+f", "\ufb00")
            put("f+", "\ufb00")
            put("fi", "\ufb01")
            put("fl", "\ufb02")
            put("ffi", "\ufb03")
            put("ffl", "\ufb04")
            put("^G", "\u011c")
            put("^g", "\u011d")
            put("UG", "\u011e")
            put("bG", "\u011e")
            put("Ug", "\u011f")
            put("bg", "\u011f")
            put(".G", "\u0120")
            put(".g", "\u0121")
            put(",G", "\u0122")
            put(",g", "\u0123")
            put("^H", "\u0124")
            put("^h", "\u0125")
            put("/H", "\u0126")
            put("/h", "\u0127")
            put("~I", "\u0128")
            put("~i", "\u0129")
            put("_I", "\u012a")
            put("_i", "\u012b")
            put("UI", "\u012c")
            put("bI", "\u012c")
            put("Ui", "\u012d")
            put("bi", "\u012d")
            put(";I", "\u012e")
            put(",I", "\u012e")
            put(";i", "\u012f")
            put(",i", "\u012f")
            put(".I", "\u0130")
            put("i.", "\u0131")
            put("^J", "\u0134")
            put("^j", "\u0135")
            put(",K", "\u0136")
            put(",k", "\u0137")
            put("kk", "\u0138")
            put("'L", "\u0139")
            put("'l", "\u013a")
            put(",L", "\u013b")
            put(",l", "\u013c")
            put("cL", "\u013d")
            put("cl", "\u013e")
            put("/L", "\u0141")
            put("/l", "\u0142")
            put("'N", "\u0143")
            put("'n", "\u0144")
            put(",N", "\u0145")
            put(",n", "\u0146")
            put("cN", "\u0147")
            put("cn", "\u0148")
            put("NG", "\u014a")
            put("ng", "\u014b")
            put("_O", "\u014c")
            put("_o", "\u014d")
            put("UO", "\u014e")
            put("bO", "\u014e")
            put("Uo", "\u014f")
            put("bo", "\u014f")
            put("=O", "\u0150")
            put("=o", "\u0151")
            put("'R", "\u0154")
            put("'r", "\u0155")
            put(",R", "\u0156")
            put(",r", "\u0157")
            put("cR", "\u0158")
            put("cr", "\u0159")
            put("'S", "\u015a")
            put("'s", "\u015b")
            put("^S", "\u015c")
            put("^s", "\u015d")
            put(",S", "\u015e")
            put(",s", "\u015f")
            put("cS", "\u0160")
            put("cs", "\u0161")
            put(",T", "\u0162")
            put(",t", "\u0163")
            put("cT", "\u0164")
            put("ct", "\u0165")
            put("/T", "\u0166")
            put("/t", "\u0167")
            put("~U", "\u0168")
            put("~u", "\u0169")
            put("_U", "\u016a")
            put("_u", "\u016b")
            put("UU", "\u016c")
            put("bU", "\u016c")
            put("Uu", "\u016d")
            put("uu", "\u016d")
            put("bu", "\u016d")
            put("oU", "\u016e")
            put("ou", "\u016f")
            put("=U", "\u0170")
            put("=u", "\u0171")
            put(";U", "\u0172")
            put(",U", "\u0172")
            put(";u", "\u0173")
            put(",u", "\u0173")
            put("^W", "\u0174")
            put("^w", "\u0175")
            put("^Y", "\u0176")
            put("^y", "\u0177")
            put("\"Y", "\u0178")
            put("'Z", "\u0179")
            put("'z", "\u017a")
            put(".Z", "\u017b")
            put(".z", "\u017c")
            put("cZ", "\u017d")
            put("cz", "\u017e")
            put("/b", "\u0180")
            put("/I", "\u0197")
            put("+O", "\u01a0")
            put("+o", "\u01a1")
            put("+U", "\u01af")
            put("+u", "\u01b0")
            put("/Z", "\u01b5")
            put("/z", "\u01b6")
            put("cA", "\u01cd")
            put("ca", "\u01ce")
            put("cI", "\u01cf")
            put("ci", "\u01d0")
            put("cO", "\u01d1")
            put("co", "\u01d2")
            put("cU", "\u01d3")
            put("cu", "\u01d4")
            put("_\u00dc", "\u01d5")
            put("_\"U", "\u01d5")
            put("_\u00fc", "\u01d6")
            put("_\"u", "\u01d6")
            put("'\u00dc", "\u01d7")
            put("'\"U", "\u01d7")
            put("'\u00fc", "\u01d8")
            put("'\"u", "\u01d8")
            put("c\u00dc", "\u01d9")
            put("c\"U", "\u01d9")
            put("c\u00fc", "\u01da")
            put("c\"u", "\u01da")
            put("`\u00dc", "\u01db")
            put("`\"U", "\u01db")
            put("`\u00fc", "\u01dc")
            put("`\"u", "\u01dc")
            put("_\u00c4", "\u01de")
            put("_\"A", "\u01de")
            put("_\u00e4", "\u01df")
            put("_\"a", "\u01df")
            put("_.\u0041", "\u01e0")
            put("_.a", "\u01e1")
            put("_\u00c6", "\u01e2")
            put("_\u00e6", "\u01e3")
            put("/G", "\u01e4")
            put("/g", "\u01e5")
            put("cG", "\u01e6")
            put("cg", "\u01e7")
            put("cK", "\u01e8")
            put("ck", "\u01e9")
            put(";O", "\u01ea")
            put(";o", "\u01eb")
            put("_;O", "\u01ec")
            put("_;o", "\u01ed")
            put("cj", "\u01f0")
            put("'G", "\u01f4")
            put("'g", "\u01f5")
            put("`N", "\u01f8")
            put("`n", "\u01f9")
            put("'\u00c5", "\u01fa")
            put("o'A", "\u01fa")
            put("'\u00e5", "\u01fb")
            put("o'a", "\u01fb")
            put("'\u00c6", "\u01fc")
            put("'\u00e6", "\u01fd")
            put("'\u00d8", "\u01fe")
            put("'/O", "\u01fe")
            put("'\u00f8", "\u01ff")
            put("'/o", "\u01ff")
            put("cH", "\u021e")
            put("ch", "\u021f")
            put(".A", "\u0226")
            put(".a", "\u0227")
            put("_\u00d6", "\u022a")
            put("_\"O", "\u022a")
            put("_\u00f6", "\u022b")
            put("_\"o", "\u022b")
            put("_\u00d5", "\u022c")
            put("_~O", "\u022c")
            put("_\u00f5", "\u022d")
            put("_~o", "\u022d")
            put(".O", "\u022e")
            put(".o", "\u022f")
            put("_.O", "\u0230")
            put("_.o", "\u0231")
            put("_Y", "\u0232")
            put("_y", "\u0233")
            put("ee", "\u0259")
            put("/i", "\u0268")
            put("^_h", "\u02b0")
            put("^_j", "\u02b2")
            put("^_r", "\u02b3")
            put("^_w", "\u02b7")
            put("^_y", "\u02b8")
            put("^_l", "\u02e1")
            put("^_s", "\u02e2")
            put("^_x", "\u02e3")
            put("\"'", "\u0344")
            put(".B", "\u1e02")
            put(".b", "\u1e03")
            put("!B", "\u1e04")
            put("!b", "\u1e05")
            put("'\u00c7", "\u1e08")
            put("'\u00e7", "\u1e09")
            put(".D", "\u1e0a")
            put(".d", "\u1e0b")
            put("!D", "\u1e0c")
            put("!d", "\u1e0d")
            put(",D", "\u1e10")
            put(",d", "\u1e11")
            put("`\u0112", "\u1e14")
            put("`_E", "\u1e14")
            put("`\u0113", "\u1e15")
            put("`_e", "\u1e15")
            put("'\u0112", "\u1e16")
            put("'_E", "\u1e16")
            put("'\u0113", "\u1e17")
            put("'_e", "\u1e17")
            put("U,E", "\u1e1c")
            put("b,E", "\u1e1c")
            put("U,e", "\u1e1d")
            put("b,e", "\u1e1d")
            put(".F", "\u1e1e")
            put(".f", "\u1e1f")
            put("_G", "\u1e20")
            put("_g", "\u1e21")
            put(".H", "\u1e22")
            put(".h", "\u1e23")
            put("!H", "\u1e24")
            put("!h", "\u1e25")
            put("\"H", "\u1e26")
            put("\"h", "\u1e27")
            put(",H", "\u1e28")
            put(",h", "\u1e29")
            put("'\u00cf", "\u1e2e")
            put("'\"I", "\u1e2e")
            put("'\u00ef", "\u1e2f")
            put("'\"i", "\u1e2f")
            put("'K", "\u1e30")
            put("'k", "\u1e31")
            put("!K", "\u1e32")
            put("!k", "\u1e33")
            put("!L", "\u1e36")
            put("!l", "\u1e37")
            put("_!L", "\u1e38")
            put("_!l", "\u1e39")
            put("'M", "\u1e3e")
            put("'m", "\u1e3f")
            put(".M", "\u1e40")
            put(".m", "\u1e41")
            put("!M", "\u1e42")
            put("!m", "\u1e43")
            put(".N", "\u1e44")
            put(".n", "\u1e45")
            put("!N", "\u1e46")
            put("!n", "\u1e47")
            put("'\u00d5", "\u1e4c")
            put("'~O", "\u1e4c")
            put("'\u00f5", "\u1e4d")
            put("'~o", "\u1e4d")
            put("\"\u00d5", "\u1e4e")
            put("\"~O", "\u1e4e")
            put("\"\u00f5", "\u1e4f")
            put("\"~o", "\u1e4f")
            put("`\u014c", "\u1e50")
            put("`_O", "\u1e50")
            put("`\u014d", "\u1e51")
            put("`_o", "\u1e51")
            put("'\u014c", "\u1e52")
            put("'_O", "\u1e52")
            put("'\u014d", "\u1e53")
            put("'_o", "\u1e53")
            put("'P", "\u1e54")
            put("'p", "\u1e55")
            put(".P", "\u1e56")
            put(".p", "\u1e57")
            put(".R", "\u1e58")
            put(".r", "\u1e59")
            put("!R", "\u1e5a")
            put("!r", "\u1e5b")
            put("_!R", "\u1e5c")
            put("_!r", "\u1e5d")
            put(".S", "\u1e60")
            put(".s", "\u1e61")
            put("!S", "\u1e62")
            put("!s", "\u1e63")
            put(".\u015a", "\u1e64")
            put(".'S", "\u1e64")
            put(".\u015b", "\u1e65")
            put(".'s", "\u1e65")
            put(".\u0160", "\u1e66")
            put(".\u0161", "\u1e67")
            put(".!S", "\u1e68")
            put(".!s", "\u1e69")
            put(".T", "\u1e6a")
            put(".t", "\u1e6b")
            put("!T", "\u1e6c")
            put("!t", "\u1e6d")
            put("'\u0168", "\u1e78")
            put("'~U", "\u1e78")
            put("'\u0169", "\u1e79")
            put("'~u", "\u1e79")
            put("\"\u016a", "\u1e7a")
            put("\"_U", "\u1e7a")
            put("\"\u016b", "\u1e7b")
            put("\"_u", "\u1e7b")
            put("~V", "\u1e7c")
            put("~v", "\u1e7d")
            put("!V", "\u1e7e")
            put("!v", "\u1e7f")
            put("`W", "\u1e80")
            put("`w", "\u1e81")
            put("'W", "\u1e82")
            put("'w", "\u1e83")
            put("\"W", "\u1e84")
            put("\"w", "\u1e85")
            put(".W", "\u1e86")
            put(".w", "\u1e87")
            put("!W", "\u1e88")
            put("!w", "\u1e89")
            put(".X", "\u1e8a")
            put(".x", "\u1e8b")
            put("\"X", "\u1e8c")
            put("\"x", "\u1e8d")
            put(".Y", "\u1e8e")
            put(".y", "\u1e8f")
            put("^Z", "\u1e90")
            put("^z", "\u1e91")
            put("!Z", "\u1e92")
            put("!z", "\u1e93")
            put("\"t", "\u1e97")
            put("ow", "\u1e98")
            put("oy", "\u1e99")
            put("!A", "\u1ea0")
            put("!a", "\u1ea1")
            put("?A", "\u1ea2")
            put("?a", "\u1ea3")
            put("'\u00c2", "\u1ea4")
            put("'^A", "\u1ea4")
            put("'\u00e2", "\u1ea5")
            put("'^a", "\u1ea5")
            put("`\u00c2", "\u1ea6")
            put("`^A", "\u1ea6")
            put("`\u00e2", "\u1ea7")
            put("`^a", "\u1ea7")
            put("?\u00c2", "\u1ea8")
            put("?^A", "\u1ea8")
            put("?\u00e2", "\u1ea9")
            put("?^a", "\u1ea9")
            put("~\u00c2", "\u1eaa")
            put("~^A", "\u1eaa")
            put("~\u00e2", "\u1eab")
            put("~^a", "\u1eab")
            put("^!A", "\u1eac")
            put("^!a", "\u1ead")
            put("'\u0102", "\u1eae")
            put("'bA", "\u1eae")
            put("'\u0103", "\u1eaf")
            put("'ba", "\u1eaf")
            put("`\u0102", "\u1eb0")
            put("`bA", "\u1eb0")
            put("`\u0103", "\u1eb1")
            put("`ba", "\u1eb1")
            put("?\u0102", "\u1eb2")
            put("?bA", "\u1eb2")
            put("?\u0103", "\u1eb3")
            put("?ba", "\u1eb3")
            put("~\u0102", "\u1eb4")
            put("~bA", "\u1eb4")
            put("~\u0103", "\u1eb5")
            put("~ba", "\u1eb5")
            put("U!A", "\u1eb6")
            put("b!A", "\u1eb6")
            put("U!a", "\u1eb7")
            put("b!a", "\u1eb7")
            put("!E", "\u1eb8")
            put("!e", "\u1eb9")
            put("?E", "\u1eba")
            put("?e", "\u1ebb")
            put("~E", "\u1ebc")
            put("~e", "\u1ebd")
            put("'\u00ca", "\u1ebe")
            put("'^E", "\u1ebe")
            put("'\u00ea", "\u1ebf")
            put("'^e", "\u1ebf")
            put("`\u00ca", "\u1ec0")
            put("`^E", "\u1ec0")
            put("`\u00ea", "\u1ec1")
            put("`^e", "\u1ec1")
            put("?\u00ca", "\u1ec2")
            put("?^E", "\u1ec2")
            put("?\u00ea", "\u1ec3")
            put("?^e", "\u1ec3")
            put("~\u00ca", "\u1ec4")
            put("~^E", "\u1ec4")
            put("~\u00ea", "\u1ec5")
            put("~^e", "\u1ec5")
            put("^!E", "\u1ec6")
            put("^!e", "\u1ec7")
            put("?I", "\u1ec8")
            put("?i", "\u1ec9")
            put("!I", "\u1eca")
            put("!i", "\u1ecb")
            put("!O", "\u1ecc")
            put("!o", "\u1ecd")
            put("?O", "\u1ece")
            put("?o", "\u1ecf")
            put("'\u00d4", "\u1ed0")
            put("'^O", "\u1ed0")
            put("'\u00f4", "\u1ed1")
            put("'^o", "\u1ed1")
            put("`\u00d4", "\u1ed2")
            put("`^O", "\u1ed2")
            put("`\u00f4", "\u1ed3")
            put("`^o", "\u1ed3")
            put("?\u00d4", "\u1ed4")
            put("?^O", "\u1ed4")
            put("?\u00f4", "\u1ed5")
            put("?^o", "\u1ed5")
            put("~\u00d4", "\u1ed6")
            put("~^O", "\u1ed6")
            put("~\u00f4", "\u1ed7")
            put("~^o", "\u1ed7")
            put("^!O", "\u1ed8")
            put("^!o", "\u1ed9")
            put("'\u01a0", "\u1eda")
            put("'+O", "\u1eda")
            put("'\u01a1", "\u1edb")
            put("'+o", "\u1edb")
            put("`\u01a0", "\u1edc")
            put("`+O", "\u1edc")
            put("`\u01a1", "\u1edd")
            put("`+o", "\u1edd")
            put("?\u01a0", "\u1ede")
            put("?+O", "\u1ede")
            put("?\u01a1", "\u1edf")
            put("?+o", "\u1edf")
            put("~\u01a0", "\u1ee0")
            put("~+O", "\u1ee0")
            put("~\u01a1", "\u1ee1")
            put("~+o", "\u1ee1")
            put("!\u01a0", "\u1ee2")
            put("!+O", "\u1ee2")
            put("!\u01a1", "\u1ee3")
            put("!+o", "\u1ee3")
            put("!U", "\u1ee4")
            put("!u", "\u1ee5")
            put("?U", "\u1ee6")
            put("?u", "\u1ee7")
            put("'\u01af", "\u1ee8")
            put("'+U", "\u1ee8")
            put("'\u01b0", "\u1ee9")
            put("'+u", "\u1ee9")
            put("`\u01af", "\u1eea")
            put("`+U", "\u1eea")
            put("`\u01b0", "\u1eeb")
            put("`+u", "\u1eeb")
            put("?\u01af", "\u1eec")
            put("?+U", "\u1eec")
            put("?\u01b0", "\u1eed")
            put("?+u", "\u1eed")
            put("~\u01af", "\u1eee")
            put("~+U", "\u1eee")
            put("~\u01b0", "\u1eef")
            put("~+u", "\u1eef")
            put("!\u01af", "\u1ef0")
            put("!+U", "\u1ef0")
            put("!\u01b0", "\u1ef1")
            put("!+u", "\u1ef1")
            put("`Y", "\u1ef2")
            put("`y", "\u1ef3")
            put("!Y", "\u1ef4")
            put("!y", "\u1ef5")
            put("?Y", "\u1ef6")
            put("?y", "\u1ef7")
            put("~Y", "\u1ef8")
            put("~y", "\u1ef9")
            put("^0", "\u2070")
            put("^_i", "\u2071")
            put("^4", "\u2074")
            put("^5", "\u2075")
            put("^6", "\u2076")
            put("^7", "\u2077")
            put("^8", "\u2078")
            put("^9", "\u2079")
            put("^+", "\u207a")
            put("^=", "\u207c")
            put("^(", "\u207d")
            put("^)", "\u207e")
            put("^_n", "\u207f")
            put("_0", "\u2080")
            put("_1", "\u2081")
            put("_2", "\u2082")
            put("_3", "\u2083")
            put("_4", "\u2084")
            put("_5", "\u2085")
            put("_6", "\u2086")
            put("_7", "\u2087")
            put("_8", "\u2088")
            put("_9", "\u2089")
            put("_+", "\u208a")
            put("_=", "\u208c")
            put("_(", "\u208d")
            put("_)", "\u208e")
            put("SM", "\u2120")
            put("sM", "\u2120")
            put("Sm", "\u2120")
            put("sm", "\u2120")
            put("TM", "\u2122")
            put("tM", "\u2122")
            put("Tm", "\u2122")
            put("tm", "\u2122")
            put("13", "\u2153")
            put("23", "\u2154")
            put("15", "\u2155")
            put("25", "\u2156")
            put("35", "\u2157")
            put("45", "\u2158")
            put("16", "\u2159")
            put("56", "\u215a")
            put("18", "\u215b")
            put("38", "\u215c")
            put("58", "\u215d")
            put("78", "\u215e")
            put("/\u2190", "\u219a")
            put("/\u2192", "\u219b")
            put("<-", "\u2190")
            put("->", "\u2192")
            put("/=", "\u2260")
            put("=/", "\u2260")
            put("<=", "\u2264")
            put(">=", "\u2265")
            put("(1)", "\u2460")
            put("(2)", "\u2461")
            put("(3)", "\u2462")
            put("(4)", "\u2463")
            put("(5)", "\u2464")
            put("(6)", "\u2465")
            put("(7)", "\u2466")
            put("(8)", "\u2467")
            put("(9)", "\u2468")
            put("(10)", "\u2469")
            put("(11)", "\u246a")
            put("(12)", "\u246b")
            put("(13)", "\u246c")
            put("(14)", "\u246d")
            put("(15)", "\u246e")
            put("(16)", "\u246f")
            put("(17)", "\u2470")
            put("(18)", "\u2471")
            put("(19)", "\u2472")
            put("(20)", "\u2473")
            put("(A)", "\u24b6")
            put("(B)", "\u24b7")
            put("(C)", "\u24b8")
            put("(D)", "\u24b9")
            put("(E)", "\u24ba")
            put("(F)", "\u24bb")
            put("(G)", "\u24bc")
            put("(H)", "\u24bd")
            put("(I)", "\u24be")
            put("(J)", "\u24bf")
            put("(K)", "\u24c0")
            put("(L)", "\u24c1")
            put("(M)", "\u24c2")
            put("(N)", "\u24c3")
            put("(O)", "\u24c4")
            put("(P)", "\u24c5")
            put("(Q)", "\u24c6")
            put("(R)", "\u24c7")
            put("(S)", "\u24c8")
            put("(T)", "\u24c9")
            put("(U)", "\u24ca")
            put("(V)", "\u24cb")
            put("(W)", "\u24cc")
            put("(X)", "\u24cd")
            put("(Y)", "\u24ce")
            put("(Z)", "\u24cf")
            put("(a)", "\u24d0")
            put("(b)", "\u24d1")
            put("(c)", "\u24d2")
            put("(d)", "\u24d3")
            put("(e)", "\u24d4")
            put("(f)", "\u24d5")
            put("(g)", "\u24d6")
            put("(h)", "\u24d7")
            put("(i)", "\u24d8")
            put("(j)", "\u24d9")
            put("(k)", "\u24da")
            put("(l)", "\u24db")
            put("(m)", "\u24dc")
            put("(n)", "\u24dd")
            put("(o)", "\u24de")
            put("(p)", "\u24df")
            put("(q)", "\u24e0")
            put("(r)", "\u24e1")
            put("(s)", "\u24e2")
            put("(t)", "\u24e3")
            put("(u)", "\u24e4")
            put("(v)", "\u24e5")
            put("(w)", "\u24e6")
            put("(x)", "\u24e7")
            put("(y)", "\u24e8")
            put("(z)", "\u24e9")
            put("(0)", "\u24ea")
            put("(21)", "\u3251")
            put("(22)", "\u3252")
            put("(23)", "\u3253")
            put("(24)", "\u3254")
            put("(25)", "\u3255")
            put("(26)", "\u3256")
            put("(27)", "\u3257")
            put("(28)", "\u3258")
            put("(29)", "\u3259")
            put("(30)", "\u325a")
            put("(31)", "\u325b")
            put("(32)", "\u325c")
            put("(33)", "\u325d")
            put("(34)", "\u325e")
            put("(35)", "\u325f")
            put("(36)", "\u32b1")
            put("(37)", "\u32b2")
            put("(38)", "\u32b3")
            put("(39)", "\u32b4")
            put("(40)", "\u32b5")
            put("(41)", "\u32b6")
            put("(42)", "\u32b7")
            put("(43)", "\u32b8")
            put("(44)", "\u32b9")
            put("(45)", "\u32ba")
            put("(46)", "\u32bb")
            put("(47)", "\u32bc")
            put("(48)", "\u32bd")
            put("(49)", "\u32be")
            put("(50)", "\u32bf")
            put("\\o/", "\uD83D\uDE4C")
        }
    }
}
